### ISSUE TITLE
Stuck on "Lade ..."

### ISSUE THREAD

**Issue by eleven29** [JockeyDoe/MMM-Autobahn#1]
Hi,

freue mich schon sehr darauf, das ans Laufen zu kriegen! Leider komme ich nach der Installation über die "Lade ..."-Information des Plugins nicht hinaus. Selbst mit der angegebenen Beispielkonfiguration bleibt das Plugin beim Laden hängen und zeigt weder Meldungen an, noch die Info, dass keine vorliegen. 
Ich bin leider recht neu in der Magic-Mirror-Welt, aber wenn ich irgendwas tun kann, um beim Troubleshooting zu helfen, lass es mich bitte wissen.

very eager to get this up and running. However after installing this plugin the display gets stuck on "Loading ...". I reverted my custom config back to your example and I still can't get past the loading info. 
I'm really new to MM² in general but if there is anything I can do to help troubleshoot, please let me know.

--Yannick

**Comment by JockeyDoe** [comment]
Hi,

danke für dein Interesse an meinem Plugin! Ich denke, dass ein Problem mit der Konfiguration vorliegt. Würdest du den relevanten Teil deiner config.js hier teilen? Ansonsten kannst du es auch mal mit der Standard-Config probieren, also im Bereich config des Plugins nichts weiter eintragen.

Grüße

**Comment by eleven29** [comment]
Hey! Ich hatte es mit der Standard-Config versucht, aber ohne Erfolg. War aber trotzdem user error, weil ich einfach vergessen hatte, nach der Installation den Server neu zu starten. Seitdem läuft es ohne Probleme. 
Danke noch mal für das tolle Plugin und die schnelle Reaktion!

**Comment by JockeyDoe** [comment]
Freut mich, dass es jetzt funktioniert!
