### ISSUE TITLE
Meldung: "Lade..."

### ISSUE THREAD

**Issue by Coernel82** [JockeyDoe/MMM-Autobahn#2]
Das Modul funktionierte von Anfang an, zeigt aber plötzlich nur noch ``Lade...`` an. Auf Verdacht, dass dieses erscheint, sofern keine Verkehrsmeldungen vorhanden sind, habe ich gezielt Autobahnen mit Meldungen hinzugefügt und der Fehler bleibt bestehen.
Gibt es eine Möglichkeit, wie ich helfen kann, den Fehler zu finden?

**Comment by JockeyDoe** [comment]
Hi!
Wenn keine Meldung vorhanden ist, gibt es einen entsprechenden anderen Text. Wird nur "Lade..." angezeigt, deutet das auf einen Fehler im Plugin oder der Konfiguration hin.
Zunächst kannst du mal probieren, die A661 hinzuzufügen (Und alles andere mal rauszuwerfen). Hier befindet sich eine Meldung, die bis 2026 bestehen bleiben wird. 
Meine Vermutung ist, dass bei einer deiner ausgewählten Straßen eine Meldung mit einer Formatierung (o.Ä.) vorliegt, die ich bei der Erstellung des Plugins nicht berücksichtigt habe. 
Ich würde dich außerdem bitten, mir den relevanten Teil deiner Konfigurationsdatei zu senden, damit ich den Fehler nachvollziehen kann.

**Comment by Coernel82** [comment]
A661 habe ich hinzugefügt, die anderen auskommentiert. Ändert leider nichts!

```java
// andere Module
				{
			module: 'MMM-Autobahn',
			header: 'Verkehrsmeldungen',
			position: "bottom_center",
			config: {
				reloadInterval: 1000 * 60 * 20, 
				logo_right: false,
				roads: [
/* 					{
						road: "A4",
						from: 22,
						to: 16,
					},
					{
						road: "A1",
					},
					{
						road: "A45",
					}, */
					{
						road: "A661",
					},
				]
			}
		},
// andere Module
```

**Comment by Coernel82** [comment]
Nachtrag: A1 und A45 haben in ihren Beschreibungen Sonderzeichen: Münster, Lüdenscheid, Gießen!

**Comment by Coernel82** [comment]
Plötzlich werden die A661 Warnungen angezeigt - ich aktiviere jetzt wieder A4, A1 und A45 und melde mich dann.

**Comment by Coernel82** [comment]
Also Bestätigung: Nur mit der A661 klappt es sofort wieder!

**Comment by JockeyDoe** [comment]
Ich habe das Problem gefunden und auch schon einen Fix vorbereitet. Dieser kommt morgen. 
Bis dahin ist der Workaround, die A4 komplett (also ohne 'from' und 'to' Parameter) oder gar nicht anzuzeigen.

**Comment by JockeyDoe** [comment]
Ich habe die Änderung publiziert und würde dich bitten, es noch einmal ein paar Tage lang zu testen.
Grüße und schöne Weihnachten

**Comment by Coernel82** [comment]
Habe gepullt (nicht gepullert,😉) und teste! Melde mich die nächsten Tage zurück! 🎅🎄🤶🎄🎅
