### ISSUE TITLE
1 Verkehrswarnung hängt seit ca. 2 Wochen

### ISSUE THREAD

**Issue by AWSW-de** [JockeyDoe/MMM-Autobahn#5]
Hallo,

erst mal Danke für das schöne Modul. 

Ich habe aktuell 1 Verkehrswarnung zu einer ungesicherten Unfallstelle, die seit ca. 2 Wochen dauernd angezeigt wird…

Ich habe den Modulordner schon gelöscht und das Modul neu installiert und natürlich den MM schon neu gebootet… 

Kannst Du mir einen Tipp geben, wie ich diesen offensichtlichen Cache löschen kann?

Auf der Autobahn wird die Meldung natürlich nicht mehr in den Stauinfos gemeldet. 

Danke für einen Hinweis vorab. =)

**Comment by AWSW-de** [comment]
Habe das Modul gelöscht.

**Comment by JockeyDoe** [comment]
Hi, sorry, ich habe tatsächlich das gleiche Problem. Deine erste Nachricht ist bei mir leider untergegangen. Zeitlich ist es etwas eng bei mir im Moment, so dass ich mich aktuell nicht darum kümmern kann. Ich melde mich, sobald ich etwas weiß.

**Comment by JockeyDoe** [comment]
Das Modul funktioniert nun wieder mit dem neuesten Commit
