### ISSUE TITLE
Bleibt bei Laden hängen.

### ISSUE THREAD

**Issue by JLPICAR** [JockeyDoe/MMM-Autobahn#6]
Hey,
Das Modul hat bei mir leider das Problem, dass es keine Störungen anzeigt und dauerhaft auf Laden...   gestellt ist. Hast jemand ne Idee?

Config ist schon neu gemacht und Modul habe ich auch schon neu installiert.

**Comment by MichiScl** [comment]
Habe das selbe Problem ...
Das Modul hat vor ein paar Wochen noch super funktioniert. Jetzt kommt bei mir der Fehler :
`UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'length')
1|mm       |     at /home/pi/MagicMirror/modules/MMM-Autobahn/node_helper.js:38:35
1|mm       |     at Array.forEach (<anonymous>)
1|mm       |     at Class.getData (/home/pi/MagicMirror/modules/MMM-Autobahn/node_helper.js:32:30)
1|mm       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by MichiScl** [comment]
Habe das Problem gefunden glaube ich, in der Datei "node_helper.js" wird auf ein RegEx Pattern abgefragt.

ich habe das angepasst von:
`let asNumbers = warning.title.match(/\(\d+\w*\)/g);`
zu
`let asNumbers = warning.title.match(/\d+\w*/g);`

Denke da hat sich das Format des Titels geändert, da sind nämlich keine Klammern mehr drin '/(' und '/)' habe ich aus dem RegEx entfernt. Habe es noch nicht tiefer getestet, bei mir sind aktuell keine Meldungen, aber sollte das Problem gewesen sein.

**Comment by JockeyDoe** [comment]
Das Modul funktioniert nun wieder mit dem neuesten Commit. Danke MichiScl für deine Hilfe
